package com.yxf.vehicleinspection.bean.request

/**
 *   author:yxf
 *   time:2021/12/22
 */
data class SaveInvoiceW005Request(
    val invoiceOrder : InvoiceOrder,
    val invoiceDetails : List<InvoiceDetail>
)
class InvoiceOrder(
    val Ajlsh : String,
    val Hpzl : String,
    val Hphm : String,
    val Cllx : String,
    val Czdw : String,
    val Tel : String,
    val Amout : String,
    val Buyername : String,
    val Taxnum : String,
    val Phone : String,
    val Address : String,
    val Account : String,
    val Orderno : String,
    val Clerk :String,
    val Clerkid : String,
    val Payee : String,
    val Post_identity : String,
    val Invoicedate : String,
    val Saleaccount : String,
    val Salephone : String,
    val Saleaddress : String,
    val Saletaxnum : String,
    val Checker : String ,
    val Explain : String = "#正常开票#",
    val Auditor  : String = "",
    val Status  : String = "0",
    val Fpqqlsh  : String = "",
    val Ret_message : String = "",
    val Kptype : String = "1",
    val Message : String = "",
    val Fpdm : String = "",
    val Fphm : String = "",
    val Tsfs : String = "1",
    val Email : String = "",
    val Qdbz : String = "",
    val Qdxmmc : String = "",
    val Telephone : String = "",
    val Dkbz : String = "1",
    val Deptid : String = "",
    val InvoiceLine : String = "",
    val C_orderno : String = "",
    val C_fpqqlsh : String = "",
    val C_status : String = "",
    val C_msg : String = "",
    val C_url : String = "",
    val C_jpg_url : String = "",
    val C_kprq : String = "",
    val C_fpdm : String = "",
    val C_fphm : String = "",
    val C_bhsje : String = "",
    val C_hsje : String = "",
    val C_resultmsg : String = "",
    val C_invoiceid : String = "",
    val C_buyername : String = "",
    val C_taxnum : String = "",
    val C_jym : String = "",
)

data class InvoiceDetail(
    val Orderno : String,
    val Detailno : Int,
    val Goodsname : String,
    val Num : String,
    val Price : String,
    val Hsbz : String,
    val Taxrate : String,
    val Spec : String,
    val Unit : String,
    val Spbm : String,
    val Zsbm : String,
    val Fphxz : String,
    val Yhzcbs : String,
    val Zzstsgl : String,
    val Lslbs : String,
    val Kce : String,
    val Taxfreeamt : String,
    val Tax : String,
    val Taxamt : String,
)

