package com.yxf.vehicleinspection.bean.request

/**
 *   author:yxf
 *   time:2021/12/7
 */
data class SaveVehicleInfoW003Request(
    val Id : Int,
    val Hphm : String,
    val Hpzl : String,
    val Hpys : String,
    val Clsbdh : String,
    val Cwkc : String,
    val Cwkk : String,
    val Cwkg : String,
    val Hxnbcd : String,
    val Hxnbkd : String,
    val Hxnbgd : String,
    val Zxxs : String,
    val Dzss: String,
    val Cyc: String,
    val Sfmz: String,
    val Ajywlb: String,
    val Hjywlb: String,
    val Zjjylb: String,
    val Xszbh: String,
    val Clpp1: String,
    val Clxh: String,
    val Fdjxh: String,
    val Fdjh: String,
    val Syr: String,
    val Lxdh: String,
    val Zt: String,
    val Zzcmc: String,
    val Qdzs: String,
    val Qdzw: String,
    val Zczs: String,
    val Zczw: String,
    val Zs : String,
    val Zj: String,
    val Zzs: String,
    val Qzs: String,
    val Qlj: String,
    val Hlj: String,
    val Zzl: String,
    val Zbzl: String,
    val Kqxjzw: String,
    val Zxzs: String,
    val Bzzw: String,
    val Hdzk: String,
    val Hdzzl: String,
    val Zqyzl: String,
    val Zdsjcs: String,
    val Gl: String,
    val Pl: String,
    val Pqgs: String,
    val Lcbds: String,
    val Edzs: String,
    val Ltgg: String,
    val Qgs: String,
    val Lxdz: String,
    val Sjr: String,
    val Sjrdh: String,
    val Sjrsfzh: String,
    val SCR: String,
    val DPF: String,
    val Cllx: String,
    val Clyt: String,
    val Ytsx: String,
    val Wgchx: String,
    val Gcjk: String,
    val Qdxs: String,
    val Zdly: String,
    val Rlzl: String,
    val Rygg: String,
    val Qzdz: String,
    val Jcxh: String,
    val Jdcsslb: String,
    val Gyfs: String,
    val Jqfs: String,
    val Bsxs: String,
    val Dws: String,
    val Ccs: String,
    val Hclfs: String,
    val Ccrq: String,
    val Ccdjrq: String,
    val Djrq: String,
    val Clpp2 : String,
    val Zzg : String,
    val Csys : String,
    val Syxz : String,
    val Sfzmhm : String,
    val Sfzmmc : String,
    val Yxqz : String,
    val Qzbfqz : String,
    val Fzjg : String,
    val Glbm : String,
    val Bxzzrq : String,
    val Dybj : String?,
    val Gbthps : String,
    val Lts : String,
    val Qpzk : String,
    val Hpzk : String,
    val Jyhgbzbh : String,
    val Xzqh : String,
    val Zsxzqh : String,
    val Zzxzqh : String,
    val Sfmj : String,
    val Zjywlb : String,
    val Hjxm : String?,
    val Ajcx : String?,
    val Zjcx : String?,
    val Hbdbqk : String,
    val Jcrq : String,
    val Jcsj : String,
    val Ygdltz : String?,
    val Zxzxjxs : String?,
    val Zjdw : String?,
    val Pfjd : String?,
    val Hjdlsj : String?,
    val Ajlsh : String,
    val Hjlsh : String,
    val Jyjgbh : String,
    val Xh : String,
    val JcxmAj : String,
    val JcxmHJ : String,
    val JcffHJ : String,
    val JyywZj : String,
    val Bhgx : String,
    val Dlsj : String,
    val Ajjccs : Int,
    val Hjjccs : Int,
    val Dly : String,
    val Dlysfzh : String,
    val Ycy : String,
    val Ycysfzh : String,
    val Wjy : String,
    val Wjysfzh : String,
    val Dtjyy : String,
    val Dtjyysfzh : String,
    val Dpjyy : String,
    val Dpjyysfzh : String,
    val Jcxlb : String,
    val Yyzh : String,


) {
}