package com.yxf.vehicleinspection.singleton

/**
 *   author:yxf
 *   time:2021/11/12
 */
object StaticParams {
    const val SIDE_SLIP = "A1"
    const val PARKING_BREAK = "B0"
    const val ONE_AXIS_BREAK = "B1"
    const val TWO_AXIS_BREAK = "B2"
    const val THREE_AXIS_BREAK = "B3"
    const val FOUR_AXIS_BREAK = "B4"
    const val FIVE_AXIS_BREAK = "B5"
    const val CHASSIS = "C1"
    const val POWER = "CG"
    const val DYNAMIC = "DC"
    const val EXTERIOR_FRONT = "F1"
    const val EXTERIOR_BEHIDE = "F0"
    const val LEFT_LIGHT = "H1"
    const val RIGHT_LIGHT = "H4"
    const val ONE_AXIS_LOAD_BREAK = "L1"
    const val TWO_AXIS_LOAD_BREAK = "L2"
    const val THREE_AXIS_LOAD_BREAK = "L3"
    const val FOUR_AXIS_LOAD_BREAK = "L4"
    const val EXPANDED_SIZE_FRONT= "M1"
    const val EXPANDED_SIZE_BESIDE = "M2"
    const val ROAD_TEST_BREAK_START = "R"
    const val SPEED = "S1"
    const val CURB_QUALITY_FRONT = "Z1"
    const val CURB_QUALITY_BEHIND = "Z2"
    const val RAMP_PARKING_FRONT = "R8"
    const val RAMP_PARKING_BEHIDE = "R9"
    const val VIN_FAR_TO_CLOSED = "F2"
    const val AROUND_VEHICLE = "F3"
    const val TIRE_TREAD_DEPTH = "F4"
    const val UNIQUE_FRONT = "UC"
    const val UNIQUE_BEHIND = "UC0"
    const val ONE_AXIS_PARKING_BREAK = "B01"
    const val TWO_AXIS_PARKING_BREAK = "B02"
    const val THREE_AXIS_PARKING_BREAK = "B03"
    const val FOUR_AXIS_PARKING_BREAK = "B04"
    const val FIVE_AXIS_PARKING_BREAK = "B05"
    const val ONLINE_FRONT_HJ = "100404"
    const val ONLINE_BEHIND_HJ = "100401"
    const val ONLINE_MOVE_HJ = "100402"
    const val CHASSIS_HJ = "100203"
    const val EXTERIOR_LEFT_FRONT_HJ = "100201"
    const val EXTERIOR_RIGHT_BEHIND_HJ = "100202"
}