package com.yxf.vehicleinspection.bean.response

import java.io.Serializable

/**
 *   author:yxf
 *   time:2021/11/4
 *   @param Id 编号 VARCHAR(20)
 *   @param Lsh 流水号 VARCHAR(20)
 *   @param Hphm 号牌号码 VARCAHR(24)
 *   @param Hpzl 号牌种类
 *   @param Clsbdh 车辆识别代号
 *   @param Clpp1 车辆品牌1
 *   @param Clxh 车辆型号
 *   @param Clpp2 车辆品牌2
 *   @param Gcjk 国产/进口
 *   @param Zzg 制造国
 *   @param Zzcmc 制造厂名称
 *   @param Fdjh 发动机号
 *   @param Cllx 车辆类型
 *   @param Csys 车身颜色
 *   @param Syxz 使用性质
 *   @param Sfzmhm 身份证明号码
 *   @param Sfzmmc 身份证明名称
 *   @param Syr 所有人
 *   @param Ccdjrq 初次登记日期
 *   @param Djrq 最近定检日期
 *   @param Yxqz 检验有效期止
 *   @param Qzbfqz 强制报废期止
 *   @param Fzjg 发证机关
 *   @param Glbm 管理部门
 *   @param Bxzzrq 保险终止日期
 *   @param Zt 机动车状态
 *   @param Dybj 抵押标记   2020.09.01取消字段
 *   @param Fdjxh 发动机型号
 *   @param Rlzl 燃料种类
 *   @param Pl 排量
 *   @param Gl 功率
 *   @param Zxxs 转向型式
 *   @param Cwkc 车外廓长
 *   @param Cwkk 车外廓宽
 *   @param Cwkg 车外廓高
 *   @param Hxnbcd 货箱内部长度
 *   @param Hxnbkd 货车内部宽度
 *   @param Hxnbgd 货箱内部高度
 *   @param Gbthps 钢板弹簧片数
 *   @param Zs 轴数
 *   @param Zj 轴距
 *   @param Qlj 前轮距
 *   @param Hlj 后轮距
 *   @param Ltgg 轮胎规格
 *   @param Lts 轮胎数
 *   @param Zzl 总质量
 *   @param Zbzl 整备质量
 *   @param Hdzzl 核定载质量
 *   @param Hdzk 核定载客
 *   @param Zqyzl 准牵引质量
 *   @param Qpzk 前排载客
 *   @param Hpzk 后排载客
 *   @param Ccrq 出厂日期
 *   @param Clyt 车辆用途
 *   @param Ytsx 用途属性
 *   @param Xszbh 行驶证编号
 *   @param Jyhgbzbh 检验合格标志编号
 *   @param Xzqh 行政区划
 *   @param Zsxzqh 住所地址行政区划
 *   @param Zzxzqh 联系地址行政区划
 *   @param Sfmj 是否免检
 *   @param Cyc 乘用车
 *   @param Ajywlb 安检业务类别
 *   @param Zjywlb 综检业务类别
 *   @param Hjywlb 环检业务类别
 *   @param Hjxm 环保检验方式
 *   @param Ajcx 安检车型
 *   @param Zjcx 综检车型
 *   @param Wgchx 外观车型
 *   @param Hbdbqk 环保达标情况
 *   @param Jcrq 检验日期
 *   @param Jcsj 检验时间
 *   @param Qdxs 驱动形式
 *   @param Zczs 驻车轴数
 *   @param Zczw 驻车轴位
 *   @param Zzs 主轴数
 *   @param Qzdz 前照灯制
 *   @param Ygdltz 远光独立调整
 *   @param Zxzxjxs 转向轴悬架型式
 *   @param Lcbds 里程表读数
 *   @param Qdzs 驱动轴数
 *   @param Qdzw 驱动轴位
 *   @param Sfmz 是否满载 0=空载 1=满载
 *   @param Zdsjcs 最大设计车速 km/h
 *   @param Zjdw 直接档位
 *   @param Bsxs 变速型式
 *   @param Zdly 制动力源，制动方式
 *   @param Qgs 气缸数
 *   @param Rygg 燃油规格
 *   @param Wxdw 维修单位
 *   @param Jgrq 竣工日期
 *   @param Lxdh 联系电话
 *   @param Lxdz 联系地址
 *   @param Hpys 号牌颜色
 *   @param Edzs 额定转速
 *   @param Bzzw 并装轴位
 *   @param Jdcsslb 机动车所属类别
 *   @param Jcxlb 检测线类别
 *   @param Qzs 前轴数
 *   @param Ednj 额定扭矩
 *   @param Ednjzs 额定扭矩转速
 *   @param Glbzfs 功率表征方式
 *   @param Kcdj 客车等级
 *   @param Hccsxs 货车车身形式
 *   @param Zxzs 转向轴数
 *   @param Qdzzl 驱动轴质量
 *   @param Zjjylb 综检检验类别   等级/在用
 *   @param Yyzh 营运证号
 *   @param Zjlsh 综检流水号
 *   @param Dzss 电子手刹
 *   @param Kqxjzw 空气悬架轴位
 *   @param Pfjd 环保排放阶段
 *   @param Pqgs 排气管数
 *   @param Jqfs 进气方式
 *   @param Dws 档位数
 *   @param Gyfs 供油方式
 *   @param Sjr 送检人姓名
 *   @param Sjrdh 送检人电话
 *   @param Sjrsfzh 送检人身份证号

 */
data class VehicleAllInfo005Response(
    val Id : String?,
    val Lsh : String,
    val Hphm : String,
    val Hpzl : String,
    val Clsbdh : String,
    val Clpp1 : String,
    val Clxh : String,
    val Clpp2 : String,
    val Gcjk : String,
    val Zzg : String,
    val Zzcmc : String,
    val Fdjh : String,
    val Cllx : String,
    val Csys : String,
    val Syxz : String,
    val Sfzmhm : String,
    val Sfzmmc : String,
    val Syr : String,
    val Ccdjrq : String,
    val Djrq : String,
    val Yxqz : String,
    val Qzbfqz : String,
    val Fzjg : String,
    val Glbm : String,
    val Bxzzrq : String,
    val Zt : String,
    val Dybj : String,
    val Fdjxh : String,
    val Rlzl : String,
    val Pl : String,
    val Gl : String,
    val Zxxs : String,
    val Cwkc : String,
    val Cwkk : String,
    val Cwkg : String,
    val Hxnbcd : String,
    val Hxnbkd : String,
    val Hxnbgd : String,
    val Gbthps : String,
    val Zs : String,
    val Zj : String,
    val Qlj : String,
    val Hlj : String,
    val Ltgg : String,
    val Lts : String,
    val Zzl : String,
    val Zbzl : String,
    val Hdzzl : String,
    val Hdzk : String,
    val Zqyzl : String,
    val Qpzk : String,
    val Hpzk : String,
    val Ccrq : String,
    val Clyt : String,
    val Ytsx : String,
    val Xszbh : String,
    val Jyhgbzbh : String,
    val Xzqh : String,
    val Zsxzqh : String,
    val Zzxzqh : String,
    val Sfmj : String,
    val Cyc : String,
    val Ajywlb : String,
    val Zjywlb : String,
    val Hjywlb : String,
    val Hjxm : String,
    val Ajcx : String,
    val Zjcx : String,
    val Wgchx : String,
    val Hbdbqk : String,
    val Jcrq : String,
    val Jcsj : String,
    val Qdxs : String,
    val Zczs : String,
    val Zczw : String,
    val Zzs : String,
    val Qzdz : String,
    val Ygdltz : String,
    val Zxzxjxs : String,
    val Lcbds : String,
    val Qdzs : String,
    val Qdzw : String,
    val Sfmz : String,
    val Zdsjcs : String,
    val Zjdw : String,
    val Bsxs : String,
    val Zdly : String,
    val Qgs : String,
    val Rygg : String,
    val Wxdw : String,
    val Jgrq : String,
    val Lxdh : String,
    val Lxdz : String,
    val Hpys : String,
    val Edzs : String,
    val Bzzw : String,
    val Jdcsslb : String,
    val Jcxlb : String,
    val Qzs : String,
    val Ednj : String,
    val Ednjzs : String,
    val Glbzfs : String,
    val Kcdj : String,
    val Hccsxs : String,
    val Zxzs : String,
    val Qdzzl : String,
    val Zjjylb : String,
    val Yyzh : String,
    val Zjlsh : String,
    val Dzss : String,
    val Kqxjzw : String,
    val Pfjd : String,
    val Pqgs : String,
    val Jqfs : String,
    val Dws : String,
    val Gyfs : String,
    val Sjr : String,
    val Sjrdh : String,
    val Sjrsfzh : String,
    val Hjdlsj : String
) : Serializable{
}